# 🏭 PRODUCTION ENVIRONMENT DOCKER COMPOSE
# This file is for production environment deployment
# Uses pre-built images from ECR with production configurations

version: '3.8'

services:
  backend:
    image: ${ECR_REGISTRY}/testdriven-backend-production:${IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
      - AUTO_SEED_DB=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    image: ${ECR_REGISTRY}/testdriven-frontend-production:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Production uses external RDS - no local database
  # Database connection via DATABASE_URL environment variable

volumes:
  # No local volumes in production - uses external storage
