# Docker Compose file for production

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
    depends_on:
      users-db:
        condition: service_healthy

  users-db:
    image: postgres:15-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users

