# Development overrides

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - './services/users:/usr/src/app'
    command: ["/usr/src/app/entrypoint.sh"]

  users-db:
    environment:
      - POSTGRES_DB=users_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: