version: '3.8'

services:
  backend:
    build:
      context: ./services/users
      dockerfile: Dockerfile-stage
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=staging
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/testdriven_stage
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-stage
      args:
        - REACT_APP_USERS_SERVICE_URL=http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=testdriven_stage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data

volumes:
  postgres_data_stage:
