"""Auto-migration: Schema updates

Revision ID: 4ac5524db2aa
Revises: c58d841067c2
Create Date: 2025-09-19 05:49:08.058289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac5524db2aa'
down_revision = 'c58d841067c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
