"""Add calendar event drill-down fields

Revision ID: 662993e31e52
Revises: 16db89439aa2
Create Date: 2025-09-19 04:29:19.873584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662993e31e52'
down_revision = '16db89439aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('related_transaction_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('related_loan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('related_campaign_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('related_fine_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meeting_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('attendees_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_members', sa.Integer(), nullable=True))

    with op.batch_alter_table('savings_groups', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_treasurer_member', 'group_members', ['treasurer_member_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key('fk_chair_member', 'group_members', ['chair_member_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key('fk_secretary_member', 'group_members', ['secretary_member_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_groups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_secretary_member', type_='foreignkey')
        batch_op.drop_constraint('fk_chair_member', type_='foreignkey')
        batch_op.drop_constraint('fk_treasurer_member', type_='foreignkey')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('total_members')
        batch_op.drop_column('attendees_count')
        batch_op.drop_column('meeting_type')
        batch_op.drop_column('related_fine_id')
        batch_op.drop_column('related_campaign_id')
        batch_op.drop_column('related_loan_id')
        batch_op.drop_column('related_transaction_id')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
