"""Add enhanced savings group features

Revision ID: 48434054ea3e
Revises: 2d708b80a861
Create Date: 2025-09-07 22:11:56.845052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48434054ea3e'
down_revision = '2d708b80a861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('parish', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('village', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('constitution_document_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('registration_certificate_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_registered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registration_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.Date(), nullable=True))
        batch_op.create_unique_constraint('uq_savings_groups_registration_number', ['registration_number'])

    # Update existing records with default values
    op.execute("UPDATE savings_groups SET district = 'Unknown' WHERE district IS NULL")
    op.execute("UPDATE savings_groups SET parish = 'Unknown' WHERE parish IS NULL")
    op.execute("UPDATE savings_groups SET village = 'Unknown' WHERE village IS NULL")
    op.execute("UPDATE savings_groups SET is_registered = 0 WHERE is_registered IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_groups', schema=None) as batch_op:
        batch_op.drop_constraint('uq_savings_groups_registration_number', type_='unique')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('is_registered')
        batch_op.drop_column('registration_certificate_url')
        batch_op.drop_column('constitution_document_url')
        batch_op.drop_column('village')
        batch_op.drop_column('parish')
        batch_op.drop_column('district')

    # ### end Alembic commands ###
