"""Add unique constraints to username and email

This migration adds essential unique constraints to ensure data integrity:
- Username must be unique across all users
- Email must be unique across all users

These constraints prevent duplicate registrations and ensure proper
user identification for authentication and PWA offline sync.

Revision ID: eee38439f24c
Revises: 09661241fff4
Create Date: 2025-08-26 23:10:43.979871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee38439f24c'
down_revision = '09661241fff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
