// Demo data for admin interface showcase
export const demoMembers = [
  {
    id: 1,
    name: 'Alice Nakato',
    phone: '+256701234567',
    gender: 'F',
    role: 'CHAIR',
    is_active: true,
    share_balance: 150000,
    total_contributions: 500000,
    joined_date: '2024-01-15',
    groupName: 'Kampala Women Group',
    groupId: 1,
    groupDistrict: 'Kampala',
    groupParish: 'Central',
  },
  {
    id: 2,
    name: 'John Mukasa',
    phone: '+256702345678',
    gender: 'M',
    role: 'TREASURER',
    is_active: true,
    share_balance: 125000,
    total_contributions: 400000,
    joined_date: '2024-01-20',
    groupName: 'Nakasero Traders',
    groupId: 2,
    groupDistrict: 'Kampala',
    groupParish: 'Nakasero',
  },
  {
    id: 3,
    name: 'Mary Nambi',
    phone: '+256703456789',
    gender: 'F',
    role: 'MEMBER',
    is_active: true,
    share_balance: 75000,
    total_contributions: 250000,
    joined_date: '2024-02-01',
    groupName: 'Central Market Group',
    groupId: 3,
    groupDistrict: 'Kampala',
    groupParish: 'Central',
  },
  {
    id: 4,
    name: 'Peter Ssali',
    phone: '+256704567890',
    gender: 'M',
    role: 'SECRETARY',
    is_active: false,
    share_balance: 50000,
    total_contributions: 180000,
    joined_date: '2024-01-10',
    groupName: 'Bugolobi Savings',
    groupId: 4,
    groupDistrict: 'Kampala',
    groupParish: 'Bugolobi',
  },
];

export const demoGroups = [
  {
    id: 1,
    name: 'Kampala Women Group',
    district: 'Kampala',
    parish: 'Central',
    village: 'Nakasero',
    status: 'ACTIVE',
    member_count: 15,
    max_members: 30,
    total_balance: 2500000,
    target_amount: 5000000,
    formation_date: '2024-01-01',
    active_loans_count: 2,
    meeting_frequency: 'WEEKLY',
  },
  {
    id: 2,
    name: 'Nakasero Traders',
    district: 'Kampala',
    parish: 'Nakasero',
    village: 'Commercial',
    status: 'MATURE',
    member_count: 22,
    max_members: 30,
    total_balance: 4200000,
    target_amount: 6000000,
    formation_date: '2023-08-15',
    active_loans_count: 1,
    meeting_frequency: 'WEEKLY',
  },
  {
    id: 3,
    name: 'Central Market Group',
    district: 'Kampala',
    parish: 'Central',
    village: 'Market',
    status: 'ACTIVE',
    member_count: 8,
    max_members: 25,
    total_balance: 850000,
    target_amount: 2000000,
    formation_date: '2024-03-01',
    active_loans_count: 0,
    meeting_frequency: 'BIWEEKLY',
  },
  {
    id: 4,
    name: 'Bugolobi Savings',
    district: 'Kampala',
    parish: 'Bugolobi',
    village: 'Residential',
    status: 'FORMING',
    member_count: 4,
    max_members: 20,
    total_balance: 120000,
    target_amount: 1000000,
    formation_date: '2024-11-01',
    active_loans_count: 0,
    meeting_frequency: 'WEEKLY',
  },
];

export const demoTransactions = [
  {
    id: 1,
    memberName: 'Alice Nakato',
    groupName: 'Kampala Women Group',
    amount: 50000,
    provider: 'MTN',
    transactionId: 'MTN123456789',
    phone: '+256701234567',
    status: 'PENDING',
    submittedDate: new Date(Date.now() - 1000 * 60 * 30), // 30 minutes ago
    savingType: 'PERSONAL',
  },
  {
    id: 2,
    memberName: 'John Mukasa',
    groupName: 'Nakasero Traders',
    amount: 25000,
    provider: 'Airtel',
    transactionId: 'AIR987654321',
    phone: '+256702345678',
    status: 'PENDING',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 2), // 2 hours ago
    savingType: 'ECD',
  },
  {
    id: 3,
    memberName: 'Mary Nambi',
    groupName: 'Central Market Group',
    amount: 75000,
    provider: 'MTN',
    transactionId: 'MTN555666777',
    phone: '+256703456789',
    status: 'REJECTED',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24), // 1 day ago
    savingType: 'SOCIAL',
    rejectionReason: 'Transaction ID not found in MTN records',
  },
];

export const adminCapabilities = {
  memberManagement: {
    title: 'Member Management CRUD',
    description: 'Complete member lifecycle management with admin override capabilities',
    features: [
      'View comprehensive member profiles across all groups',
      'Update member information when they cannot access accounts',
      'Record remote savings transactions on behalf of members',
      'Manage member roles and permissions',
      'Deactivate members while preserving historical data',
      'Generate member financial reports and summaries',
    ],
  },
  financialSupport: {
    title: 'Financial Support & Verification',
    description: 'Assist members with financial operations and transaction issues',
    features: [
      'Verify mobile money transactions with detailed audit trails',
      'Perform balance corrections with mandatory justification',
      'Process emergency transactions outside normal workflows',
      'Reconcile discrepancies with complete change tracking',
      'Manual verification of failed mobile money payments',
      'Generate comprehensive financial summaries for support',
    ],
  },
  groupOversight: {
    title: 'Group Oversight & Compliance',
    description: 'Monitor all groups with risk assessment and compliance management',
    features: [
      'Dashboard view of all groups with key metrics and status',
      'Risk assessment with automated health scoring',
      'Modify group settings and operational parameters',
      'Update constitution documents and registration certificates',
      'Generate detailed audit reports for compliance',
      'Impose restrictions or suspend operations when needed',
    ],
  },
  systemSettings: {
    title: 'System Administration',
    description: 'Configure system-wide settings and maintain operational integrity',
    features: [
      'Configure business rules and operational parameters',
      'Manage security settings and compliance requirements',
      'Control notification systems and user communications',
      'System backup and maintenance mode management',
      'Audit log retention and compliance reporting',
      'Performance monitoring and system health checks',
    ],
  },
};