name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  # Backend Tests
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('services/users/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        cd services/users
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      run: |
        cd services/users
        python -m flake8 project --exclude=venv

    - name: Run tests with coverage
      run: |
        cd services/users
        python -m pytest project/tests/ -v --cov=project --cov-report=html

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: backend-coverage-report
        path: services/users/htmlcov/

  # Frontend Tests
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: services/client/package-lock.json

    - name: Install dependencies
      run: |
        cd services/client
        npm ci

    - name: Run tests with coverage
      run: |
        cd services/client
        npm run coverage

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: frontend-coverage-report
        path: services/client/coverage/

  # Build Test
  build:
    name: Build Test
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: services/client/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd services/client
        npm ci

    - name: Build frontend
      run: |
        cd services/client
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: services/client/build/
